### ISSUE TITLE
Warning: `No pre-trained model found at the desired location.`

### ISSUE THREAD

**Issue by jedeka** [angmavrogiannis/B-GAP-Behavior-Guided-Action-Prediction-and-Navigation-for-Autonomous-Driving#2]
Hello,

I have a project and currently trying to use this repo as a reference. I have trained the GCN and DQN for 2000 episodes, and the corresponding directory for each run is produced (_e.g._ gcn_20211102-223451_110864/) to store the results. But when I tried to test the trained model, it outputted this warning:
```
[WARNING] No pre-trained model found at the desired location. 
```
which means that the model is not loaded, and it resulted in the car staying on the same lane and can't perform lane change. I ran the testing part with below command:

```
python experiments.py evaluate configs/HighwayEnv/env.json configs/HighwayEnv/agents/DQNAgent/gcn.json --test --episodes=10 --name-from-config --recover-from=~/Desktop/home-folder/B-GAP-Behavior-Guided-Action-Prediction-and-Navigation-for-Autonomous-Driving/rl-agents/scripts/out/HighwayEnv/DQNAgent/gcn_20211102-223451_110864/

```
Do you know what might be the reason behind this, or what's the correct command to run the test? Should we run only `/rl-agents/scripts/out/HighwayEnv/DQNAgent/.` without the produced directory?

Thanks for your help!

Note:
I ran the code on:
* Ubuntu 20.04, 
* Miniconda env., Python v3.7.11, 
*  CUDA 10.1

**Comment by angmavrogiannis** [comment]
Hey, 

Thanks for your question!

I have removed the GCN functionality, so you can only train a DQN agent for now. I just updated the repo to be compatible with latest version of highway-env. You can train a DQN agent for 10 episodes from  the rl-agents/scripts directory with the following command:

python experiments.py evaluate configs/HighwayEnv/env.json configs/HighwayEnv/agents/DQNAgent/dqn.json --train --episodes=10 --name-from-config

I am soon going to update the instructions in the repo, as in how you can choose how many aggressive/conservative cars you can add to the environment etc. I can also add the GCN implementation, but I wasn't getting good training results.

Let me know if you have any other questions.

Angelos
